name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/constructify
            
            # Pull latest code
            git pull origin main
            
            # Rebuild and restart containers (without --no-cache for faster builds)
            docker compose -f docker-compose.ssl.yml down
            docker compose -f docker-compose.ssl.yml build
            docker compose -f docker-compose.ssl.yml up -d
            
            # Wait for database to be healthy (increased time)
            echo "⏳ Waiting for database to be ready..."
            sleep 30
            
            # Wait for database health check
            for i in {1..30}; do
              if docker compose -f docker-compose.ssl.yml exec -T database mysqladmin ping -h localhost --silent; then
                echo "✅ Database is ready!"
                break
              fi
              echo "Waiting for database... ($i/30)"
              sleep 2
            done
            
            # Run migrations
            docker compose -f docker-compose.ssl.yml exec -T backend php artisan migrate --force
            
            # Clear and cache config
            docker compose -f docker-compose.ssl.yml exec -T backend php artisan config:cache
            docker compose -f docker-compose.ssl.yml exec -T backend php artisan route:cache
            docker compose -f docker-compose.ssl.yml exec -T backend php artisan view:cache
            
            # Set permissions
            docker compose -f docker-compose.ssl.yml exec -T backend chown -R www-data:www-data /var/www/html/storage
            docker compose -f docker-compose.ssl.yml exec -T backend chmod -R 775 /var/www/html/storage
            
            echo "✅ Deployment completed successfully!"

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 5m
          script: |
            cd /home/ubuntu/constructify
            docker compose -f docker-compose.ssl.yml ps
            echo "Checking application health..."
            sleep 5
            curl -f https://constructefy.ai || echo "Frontend check"
            curl -f https://constructefy.ai/api || echo "Backend check"

      - name: Notify on Success
        if: success()
        run: |
          echo "🎉 Deployment to EC2 successful!"
          echo "Website: https://constructefy.ai"
          echo "API: https://constructefy.ai/api"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Deployment failed! Check the logs above."

